### ISSUE TITLE
Realme 6 pro

### ISSUE THREAD

**Issue by ghost** [reiryuki/Hi-Res-Audio-Enabler-Magisk-Module#3]
Hello, I installed your magisk modules Dolby-Atmos-RC4-Ryuki-Mod-Magisk-Module and Hi-Res-Audio-24-Bit-Enabler-Magisk-Module, Dolby working, but 24 bit not working, my phone is Realme 6 pro, can you help me please @reiryuki 
![Screenshot_2021-03-31-05-23-50-03](https://user-images.githubusercontent.com/81664001/113082474-37850400-91e3-11eb-84b7-19075441086c.jpg)
[Pastebin, audio logcat](https://pastebin.com/Exb5HP1t)

**Comment by reiryuki** [comment]
If logcat shows still running in PCM 16 bit, mean your audio primary library is not supported for PCM 24 bit.

Apps bit width detection is only detecting .conf file not .xml file, so it's not valid anymore

**Comment by ghost** [comment]
But in device specification says support hires, dolby atmos, can't do nothing?

**Comment by reiryuki** [comment]
no idea sorry
